name: Terraform Actions Demo

on:
  push:
    branches:
      - master

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    name: Run terraform plan
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: .github/aws/